#!/bin/sh
set -x
set -e

#
# Build and cache project dependencies
#

#FIXME ENABLE
#docker pull anchor.private/afcowie/haskell:latest

#
# Copy in any changes to our build infrastructure
#

rsync -a src/ cache

#
# Install a base system
#

docker run -t -v ${PWD}/cache:/src:rw anchor.private/afcowie/haskell /src/.build/baseline
ID=`docker ps -q -l`
docker commit ${ID} anchor.private/engineering/vaultaire:baseline
docker rm ${ID}


#
# Update (or initally clone) source code and build dependencies in volume
#

docker run -t -v ${PWD}/cache:/src:rw anchor.private/engineering/vaultaire:baseline /src/.build/dependencies
ID=`docker ps -q -l`
docker commit ${ID} anchor.private/engineering/vaultaire:dependencies
#FIXME ENABLE
#docker rm ${ID}


#
# Build actual binaries.
#

docker run -t -v ${PWD}/cache:/src:rw anchor.private/engineering/vaultaire:dependencies /src/.build/application
ID=`docker ps -q -l`

# FIXME TEMPORARY?
docker commit ${ID} anchor.private/engineering/vaultaire:application
#FIXME ENABLE
#docker rm ${ID}

#
# Extract the binary artifacts
#

docker run -t -v ${PWD}/cache:/src:ro anchor.private/afcowie/debian:jessie /src/.build/release
ID=`docker ps -q -l`
docker commit ${ID} anchor.private/engineering/vaultaire:2.5.1
docker rm ${ID}

docker tag anchor.private/engineering/vaultaire:2.5.1 anchor.private/engineering/vaultaire:latest
docker push anchor.private/engineering/vaultaire:2.5.1
docker push anchor.private/engineering/vaultaire:latest

