#!/bin/sh
set -x
set -e

get () {
	if [ -d $1/.git ] ; then
		cd $1
		git pull
		cd ..
	else
		git clone https://github.com/anchor/$1
	fi
}

export HOME=/src
export PATH=/src/.cabal/bin:$PATH
cabal update

cd /src
get rados-haskell
get vaultaire-common
get marquise
get vaultaire

cd /
cabal install -j \
	/src/rados-haskell \
	/src/vaultaire-common \
	/src/marquise \
	/src/vaultaire

