#!/bin/sh
set -x
set -e

get () {
	if [ -d $1/.git ] ; then
		cd $1
		git pull
		cd ..
	else
		git clone https://github.com/anchor/$1
	fi
}

export HOME=/src
export PATH=/src/.cabal/bin:$PATH
cabal update

apt-get install ca-certificates git
apt-get install librados-dev libzmq3-dev pkg-config

cd /src
get vaultaire-common
get marquise
get vaultaire

cd /
cabal install -j --only-dependencies \
	/src/vaultaire-common \
	/src/marquise \
	/src/vaultaire

